id: IA7A6D580
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T23:11:43+00:00'
last_modified: '2022-06-07T21:46:03.801782+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5180
  title: ཇོ་བོ་རྗེ་དཔལ་ལྡན་ཨ་ཏི་ཤའི་རྣམ་ཐར་བཀའ་གདམས་ཕ་ཆོས་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3073':
      image_group_id: I1KG5238
      title: ''
      total_pages: 1136
      order: 1
      base_file: 3073.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
