id: IA7A6D580
legacy_id: P004295
ocr_import_info:
  bdrc_scan_id: W1KG5180
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T23:04:19'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T17:11:55.210592+00:00'
last_modified: 2022-09-01 01:12:37.607743
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG5180
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG5180
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཇོ་བོ་རྗེ་དཔལ་ལྡན་ཨ་ཏི་ཤའི་རྣམ་ཐར་བཀའ་གདམས་ཕ་ཆོས།
  author: ཨ་ཏི་ཤ
statistics:
  ocr_word_mean_confidence_index: 0.535425611287048
  ocr_word_median_confidence_index: 0.5199999809265137
quality: null
bases:
  I1KG5238:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5238
      total_pages: 1136
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG5238.txt
    statistics:
      ocr_word_median_confidence_index: 0.5199999809265137
      ocr_word_mean_confidence_index: 0.535425611287048
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
