id: P004295
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:08:25.154325
source_metadata:
  id: bdr:W1KG5180
  title: ཇོ་བོ་རྗེ་དཔལ་ལྡན་ཨ་ཏི་ཤའི་རྣམ་ཐར་བཀའ་གདམས་ཕ་ཆོས་
  author: ''
  volumes:
    d66a37a2c382431c9981a2bc43bc0c10:
      image_group_id: I1KG5238
      title: ''
      volume_number: 1
      total_pages: 1136
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
